# fly.toml app configuration file generated for django-fly-deploy on 2023-07-16T16:39:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "django-fly-deploy"
primary_region = "gru"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
